version: 1.0.0

# GO SDK使用的客户端部分。
client:
  # 客户端所属的组织，必须是organizations定义的组织
  organization: ZJU3
  # 日志级别
  logging:
    level: info
  # MSP证书的根路径
  cryptoconfig:
    path: /network/crypto-config

# 通道定义
channels:
  appchannel:
    orderers:
      - orderer.zjuwlan1.com
    peers:
      peer0.zjuwlan3.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.zjuwlan3.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

# 组织配置
organizations:
  ZJU3:
    mspid: "ZJU3MSP"
    cryptoPath: peerOrganizations/zjuwlan3.com/users/{username}@zjuwlan3.com/msp
    peers:
      - peer0.zjuwlan3.com
      - peer1.zjuwlan3.com

# orderer节点列表
orderers:
  orderer.zjuwlan1.com:
    url: orderer.zjuwlan1.com:7050
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: orderer.zjuwlan1.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

# peers节点列表
peers:
  # peer节点定义，可以定义多个
  peer0.zjuwlan3.com:
    # URL用于发送背书和查询请求
    url: peer0.zjuwlan3.com:7051
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: peer0.zjuwlan3.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.zjuwlan3.com:
    url: peer1.zjuwlan3.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.zjuwlan3.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer0.zjuwlan2.com:
    url: peer0.zjuwlan2.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.zjuwlan2.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.zjuwlan2.com:
    url: peer1.zjuwlan2.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.zjuwlan2.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
